# Copyright (c) Yugabyte, Inc.
#
# To analyze (without uploading to Fossa) -- for local debugging:
# fossa analyze --debug --output
#
# To analyze and upload dependencies:
# fossa analyze --debug

version: 3

project:
  id: yugabyte-db-platform

revision:
  branch: master

paths:
  only:
    - ./managed
    - ./yugabyted-ui
  exclude:
    - ./managed/src/test
